# ansible/playbook.yaml

---
- name: Generate custom values.yaml from Jinja2 template
  hosts: localhost
  gather_facts: no
  vars:
    environment: "{{ environment }}"
    version: "{{ version }}"
    deployment_time: "{{ deployment_time }}"
    output_file: "./{{ output_file }}"  # Ensure it's in the root directory
  tasks:
    - name: Render Jinja2 template to custom values.yaml
      template:
        src: templates/values-template.j2
        dest: "{{ output_file }}"  # Use the full path
