name: Generate Custom Values YAML using Ansible, Create Branch, and Raise PR

permissions:
  contents: write  # Allow the workflow to push to the repository and create PRs
  pull-requests: write  # Ensure pull request permissions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
      deployment_time:
        description: 'Time to deploy'
        required: false
        default: 'immediate'

jobs:
  generate_values:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install Ansible
      - name: Set up Python and install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          pip install ansible

      # Step 3: Generate the custom filename based on inputs
      - name: Generate custom filename
        id: generate_filename
        run: |
          echo "FILE_NAME=values-${{ github.event.inputs.environment }}-${{ github.event.inputs.version }}.yaml" >> $GITHUB_ENV

      # Step 4: Run Ansible Playbook to generate custom values.yaml
      - name: Generate custom values.yaml using Ansible
        run: |
          ansible-playbook ansible/playbook.yaml \
            -e "environment=${{ github.event.inputs.environment }}" \
            -e "version=${{ github.event.inputs.version }}" \
            -e "deployment_time=${{ github.event.inputs.deployment_time }}" \
            -e "output_file=${{ env.FILE_NAME }}"  # Pass custom file name

      # Step 5: Verify the generated file
      - name: Verify generated file
        run: |
          mv ansible/${{ env.FILE_NAME }} .
          ls -al  # List files in the working directory

      # Step 6: Configure Git user
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Step 7: Create a new temporary branch
      - name: Create temporary branch
        id: create_branch
        run: |
          BRANCH_NAME="generated-values-${{ github.event.inputs.environment }}-${{ github.event.inputs.version }}-$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
          git add "${{ env.FILE_NAME }}"
          git commit -m "Generated ${{ env.FILE_NAME }} for environment ${{ github.event.inputs.environment }} and version ${{ github.event.inputs.version }}"
          git push origin $BRANCH_NAME

      # Step 8: Create a pull request
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = process.env.BRANCH_NAME;
            const prTitle = `Generated ${{ env.FILE_NAME }} for environment ${{ github.event.inputs.environment }} and version ${{ github.event.inputs.version }}`;
            const prBody = `This PR includes the generated ${process.env.FILE_NAME} for the environment \`${{ github.event.inputs.environment }}\` and version \`${{ github.event.inputs.version }}\``;

            // Using github.rest to access the Pull Request API
            const pullRequest = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              body: prBody,
              head: branchName,
              base: 'main'
            });

            console.log(`Pull Request created: ${pullRequest.data.html_url}`);
