name: Generate Deployment YAML and Push to Main

permissions:
  contents: write  # Allow the workflow to push to the repository

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
      deployment_time:
        description: 'Time to deploy'
        required: false
        default: 'immediate'

jobs:
  generate_deployment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install Jinja2
      - name: Set up Python and install Jinja2
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Jinja2
        run: pip install Jinja2

      # Step 3: Generate the deployment.yaml file using Python script
      - name: Render Jinja template to generate deployment.yaml
        run: |
         
