name: Substitute Deployment YAML

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
      deployment_time:
        description: 'Time to deploy'
        required: false
        default: 'immediate'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Replace placeholders in the deployment.yaml file
    - name: Substitute values in deployment.yaml
      run: |
        sed -i 's/ENV_PLACEHOLDER/${{ github.event.inputs.environment }}/g' config/deployment.yaml
        sed -i 's/VERSION_PLACEHOLDER/${{ github.event.inputs.version }}/g' config/deployment.yaml
        sed -i 's/DEPLOYMENT_TIME_PLACEHOLDER/${{ github.event.inputs.deployment_time }}/g' config/deployment.yaml

    # Step 3: Display the updated deployment.yaml
    - name: Show updated deployment.yaml
      run: cat config/deployment.yaml

    # (Optional) Step 4: Continue with deployment process, using the updated YAML file
